# Generated by Django 5.0.4 on 2024-06-07 17:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('purchase_price', models.FloatField(default=0)),
                ('sale_price', models.FloatField(default=0)),
                ('data_criacao', models.DateField(default=datetime.datetime.today)),
                ('category_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_cate', to='venda.category')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('payment_method', models.CharField(max_length=25)),
                ('purchase_status', models.BooleanField(default=False)),
                ('purchase_date', models.DateField(default=datetime.datetime.today)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_client', to='venda.client')),
                ('product_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_product', to='venda.product')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField(default=0)),
                ('minimum_stock', models.IntegerField(default=0)),
                ('maximum_stock', models.IntegerField(default=0)),
                ('data_cadastro', models.DateField(default=datetime.datetime.today)),
                ('product_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_product', to='venda.product')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
