# Generated by Django 5.0.4 on 2024-04-21 14:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('datacriacao_cliente', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo_produto', models.CharField(max_length=15)),
                ('qtd', models.IntegerField(default=0)),
                ('preco_vendas', models.FloatField(default=0)),
                ('total_gasto', models.FloatField(default=0)),
                ('datacriacao_estoque', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor_estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_bebida', models.CharField(max_length=25)),
                ('bebida', models.CharField(max_length=25)),
                ('qtd', models.IntegerField(default=0)),
                ('valor', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('status', models.CharField(max_length=25)),
                ('data_venda', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_pagamento', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venda', to='venda.cliente')),
            ],
        ),
    ]
