# Generated by Django 5.0.4 on 2024-04-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendas',
            new_name='Venda',
        ),
    ]
