# Generated by Django 5.0.4 on 2024-06-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0003_alter_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='user_id',
            new_name='id_user',
        ),
    ]
